@Library('jenkins-shared-lib') _

pipeline {
  agent any

  environment{
    CICD_PARAMS_FOLDER = "${env.WORKSPACE}/cicd/parameters"
    SHELL_SCRIPTS_PATH = "${env.WORKSPACE}/cicd/scripts"
    EMR_ARTIFACT_PATH = "${env.WORKSPACE}/artifact"
    INFRA_PATH = "${env.WORKSPACE}/infra"
    DAGS_PATH = "${env.WORKSPACE}/dags"
    def currentTimestamp = sh(script: 'date "+%Y%m%d%H%M%S"', returnStdout: true).trim()
  }

  stages {
    stage("Checkout") {
      steps {
        checkout scm
      }
    }

    stage("Branch Configuration") {
      steps {
        sh "chmod +x -R ${env.SHELL_SCRIPTS_PATH};"
      }      

      if (!env.BITBUCKET_REPO)
      {
        env.TARGET_BRANCH = ENV
        echo("THIS IS MANUAL DEPLOYMENT ON ${env.TARGET_BRANCH}")
        loadEnv(env.TARGET_BRANCH)
      }
      else 
      {
        env.TARGET_BRANCH = "${env.BRANCH_NAME}"
        echo("THIS IS PUSH TRIGGER DEPLOYMENT ON ${env.TARGET_BRANCH}")
      }

      loadEnv(env.TARGET_BRANCH)
    }

    stage("Setting Environment Variables") {
      steps {
        script{

          parameter_file_path = "${env.CICD_PARAMS_FOLDER}/parameters.groovy"
          load "${parameter_file_path}"

          parameter_file_path = "${env.CICD_PARAMS_FOLDER}/${env.ENVIRONMENT}/parameters.groovy"
          load "${parameter_file_path}"

          env.PROJECT_ENV_TFVARS = "${env.INFRA_PATH}/tfvars/${env.ENVIRONMENT}/deploy.tfvars"
          env.PROJECT_TFVARS = "${env.INFRA_PATH}/tfvars/deploy.tfvars"
        }
      }
    }
  
    stage("Terraform Init & Apply") {
      steps {
        command = "terraform -chdir=${env.INFRA_PATH}/ init -backend-config=\"bucket=${env.TFSTATE_S3_BUCKET}\" -backend-config=\"key=${env.APP_NAME}/terraform.tfstate\" -backend-config=\"region=${env.AWS_REGION}\" -backend-config=\"dynamo_table=${env.DYNAMODB_CICD_TABLE}\""
        command = command + ";\n" + "terraform -chdir=${env.INFRA_PATH}/ plan -var-file=${PROJECT_ENV_TFVARS} -var-file=${PROJECT_TFVARS} -var=\"current_timestamp=${currentTimestamp}\""
        command = command + ";\n" + "terraform -chdir=${env.INFRA_PATH}/ apply -var-file=${PROJECT_ENV_TFVARS} -var-file=${PROJECT_TFVARS} -var=\"current_timestamp=${currentTimestamp}\" -auto-approve"
        
        echo("Deploy App Infrastructure -command: ${command}")
        
        sh "${command}"
      }
    }
  }
}
