def setEnvByBranch(String branchName) {
    if (branchName == 'develop') {
        env.ENVIRONMENT = 'dev'
    } else if (branchName=='stage') {
        env.ENVIRONMENT = 'stage'
    } else if (branchName=='production') {
        env.ENVIRONMENT = 'pro'
    }
}

pipeline {
  agent any
  environment{
    CICD_PARAMS_FOLDER = "${env.WORKSPACE}/cicd/parameters"
    SHELL_SCRIPTS_PATH = "${env.WORKSPACE}/cicd/scripts"
    EMR_ARTIFACT_PATH = "${env.WORKSPACE}/artifact"
    INFRA_PATH = "${env.WORKSPACE}/infra"
    DAGS_PATH = "${env.WORKSPACE}/dags"
  }

  parameters {
    choice(name: 'ENV', choices: ['develop', 'production'])
  }

  stages {
    stage("Checkout") {
      steps {
        checkout scm
      }
    }

    stage("Branch Configuration") {
      steps {
        script {
          sh "chmod +x -R ${env.SHELL_SCRIPTS_PATH}"

          if (!env.BITBUCKET_REPO) {
            env.TARGET_BRANCH = env.ENV
            echo "THIS IS MANUAL DEPLOYMENT ON ${env.TARGET_BRANCH}"
          } else {
            env.TARGET_BRANCH = env.BRANCH_NAME
            echo "THIS IS PUSH TRIGGER DEPLOYMENT ON ${env.TARGET_BRANCH}"
          }
          setEnvByBranch(env.TARGET_BRANCH)
          echo "SET ENV ON ${env.ENVIRONMENT}"
        }
      }
    }

    stage("Setting Environment Variables") {
      steps {
        script{

          parameter_file_path = "${env.CICD_PARAMS_FOLDER}/parameters.groovy"
          load "${parameter_file_path}"

          parameter_file_path = "${env.CICD_PARAMS_FOLDER}/${env.ENVIRONMENT}/parameters.groovy"
          load "${parameter_file_path}"

          env.PROJECT_ENV_TFVARS = "${env.INFRA_PATH}/tfvars/${env.ENVIRONMENT}/deploy.tfvars"
          env.PROJECT_TFVARS = "${env.INFRA_PATH}/tfvars/deploy.tfvars"
        }
      }
    }
  

    stage("Create EMR Serverless artifact") {
      steps {
        script {
          echo "Createing EMR job artifacts"
          sh "${env.SHELL_SCRIPTS_PATH}/create_emr_zip.sh"
        }
      }
    }

    stage("Copy Artifacts to S3") {
      steps {
          sh "aws s3 cp ${env.EMR_ARTIFACT_PATH} s3://${env.ARTIFACTS_BUCKET}/${env.APP_NAME}/ --recursive"
      }
    }

    stage("Copy DAGs to S3") {
      steps {
          sh "aws s3 cp ${env.DAGS_PATH} s3://${env.AIRFLOW_BUCKET}/dags/ --recursive"
      }
    }
  }
  post { 
      always { 
        cleanWs() 
      } 
    }
}
